FROM ghcr.io/jamesdbrock/ihaskell-notebook:master
# FROM ghcr.io/ihaskell/ihaskell-notebook:master

# Slides
RUN pip install RISE

# Notebook GitDiff (command: nbdiff-web notebook_1.ipynb notebook_2.ipynb)
# Docs: https://nbdime.readthedocs.io/en/latest/
RUN pip install nbdime

# RUN stack install Decimal http-conduit ansi-terminal
